Private Room enhancement
bogus-things/RG_ActionPatches pull request #7
Opened 2022-11-11 16:29 UTC by hawkeye-e

- Allow freely summon non bad-friend characters into private room. 
- Allow MMF and FFM options regardless of job in private room.

2022-11-12 08:25 UTC, bogus-things commented
this is awesome! have you tried to make it work outside private rooms?

2022-11-12 14:42 UTC, hawkeye-e commented
at the beginning i try to figure out how mmf situation work in job map but it always failed to load the 2nd male character
i think illusion hard coded mmf situation only apply to bad friend

2022-11-13 06:19 UTC, bogus-things commented
yeah I was seeing something similar when I tried to make MMF work in job maps. kind of a bummer they designed it like that

2022-11-13 06:26 UTC, bogus-things requested changes
looks good! if you can remove the few files I commented on from the PR to avoid conflicts, I'll go ahead and merge these changes in

2022-11-13 06:26 UTC, bogus-things commented on README.md
> -# RG_ActionPatches
could you remove this file from your PR? I don't want it to overwrite the main one

2022-11-13 06:26 UTC, bogus-things commented on src/RGActionPatches.csproj
> -      <HintPath>C:\Games\RoomGirl\BepInEx\unhollowed\Assembly-CSharp.dll</HintPath>
can you move the reference changes out of this file, too? if you make a `RGActionPatches.csproj.user` you can put them there and they'll override the properties in this file. or you can remove this file from the PR and I'll manually add the compile tags after merging

2022-11-13 06:26 UTC, bogus-things commented on src/RGActionPatchesPlugin.cs
> +        public const string Version = "0.2.0.1";
you can take this one out, too, and I'll update it post-merge

2022-11-13 11:20 UTC, hawkeye-e commented
all done!

2022-11-15 07:57 UTC, bogus-things approved these changes
Great stuff! Thanks again for putting this PR up

2022-11-15 07:58 UTC, merged